// 灵动纪念日
const app = getApp();

Page({
  data: {
    anniversaries: [],
    fixedAnniversaries: [],
    cycleAnniversaries: [],
    activeTab: 'fixed'
  },

  onLoad() {
    this.loadAnniversaries();
  },

  onShow() {
    // 页面守卫：检查是否选择了圈子
    if (!app.globalData.currentCircleId) {
      wx.redirectTo({ url: '/pages/circle/index' });
      return;
    }
    this.loadAnniversaries();
  },

  // 加载纪念日数据 - 从当前圈子获取并生成特殊纪念日
  loadAnniversaries() {
    const circleData = app.getCurrentCircleData();
    let anniversaries = circleData ? circleData.anniversaries || [] : [];

    // 生成特殊纪念日
    const autoGenerated = this.generateSpecialAnniversaries(circleData);
    anniversaries = [...anniversaries, ...autoGenerated];

    const fixed = anniversaries.filter(a => a.type === 'fixed');
    const cycle = anniversaries.filter(a => a.type === 'cycle');

    this.setData({
      anniversaries,
      fixedAnniversaries: fixed,
      cycleAnniversaries: cycle
    });
  },

  // 生成特殊纪念日
  generateSpecialAnniversaries(circleData) {
    if (!circleData || !circleData.wishes) return [];

    const wishes = circleData.wishes;
    const autoAnniversaries = [];
    const now = new Date();

    // 1. 聚餐里程碑 - 第8次聚餐、第9次聚会等
    const restaurantWishes = wishes.filter(w => w.category === 'restaurant');
    if (restaurantWishes.length >= 8) {
      autoAnniversaries.push({
        id: 'auto-food-8',
        name: `第8次聚餐`,
        type: 'fixed',
        date: now.toISOString().split('T')[0],
        autoGenerated: true,
        icon: '🍽️',
        enabled: true
      });
    }

    if (wishes.length >= 9) {
      autoAnniversaries.push({
        id: 'auto-gathering-9',
        name: `第9次聚会`,
        type: 'fixed',
        date: now.toISOString().split('T')[0],
        autoGenerated: true,
        icon: '🎉',
        enabled: true
      });
    }

    // 2. 活动一周年纪念
    wishes.forEach(wish => {
      if (wish.createdAt) {
        const createdDate = new Date(wish.createdAt);
        const oneYearLater = new Date(createdDate);
        oneYearLater.setFullYear(createdDate.getFullYear() + 1);

        // 如果今年刚好是1周年
        if (oneYearLater.getFullYear() === now.getFullYear()) {
          autoAnniversaries.push({
            id: `auto-year-${wish.id}`,
            name: `${wish.title}一周年`,
            type: 'fixed',
            date: oneYearLater.toISOString().split('T')[0],
            autoGenerated: true,
            icon: '🎂',
            enabled: true
          });
        }
      }
    });

    return autoAnniversaries;
  },

  // 切换标签
  switchTab(e) {
    const { tab } = e.currentTarget.dataset;
    this.setData({ activeTab: tab });
  },

  // 获取倒计时
  getCountdown(date) {
    if (!date) return { days: 0 };
    const now = new Date();
    const target = new Date(date);
    const thisYear = new Date(now.getFullYear(), target.getMonth(), target.getDate());

    let diff = thisYear - now;
    let year = now.getFullYear();

    // 如果已经过了今年，设置到明年
    if (diff < 0) {
      const nextYear = new Date(year + 1, target.getMonth(), target.getDate());
      diff = nextYear - now;
    }

    const days = Math.ceil(diff / (1000 * 60 * 60 * 24));
    return { days };
  },

  // 是否已过
  isPast(date) {
    if (!date) return false;
    const now = new Date();
    const target = new Date(date);
    const thisYear = new Date(now.getFullYear(), target.getMonth(), target.getDate());
    return thisYear < now;
  },

  // 获取星期几
  getWeekday(value) {
    const weekdays = ['周日', '周一', '周二', '周三', '周四', '周五', '周六'];
    return weekdays[value] || '';
  },

  // 切换开关
  toggleEnabled(e) {
    const { id } = e.currentTarget.dataset;
    const checked = e.detail.value;

    // 更新纪念日启用状态
    const anniversaries = this.data.anniversaries.map(a => {
      if (a.id === id) {
        return { ...a, enabled: checked };
      }
      return a;
    });

    // 只保存非自动生成的纪念日到当前圈子数据
    const userAnniversaries = anniversaries.filter(a => !a.autoGenerated);

    app.replaceCurrentCircleAnniversaries(userAnniversaries);

    this.setData({ anniversaries });
    this.loadAnniversaries();

    wx.showToast({
      title: checked ? '已开启提醒' : '已关闭提醒',
      icon: 'success'
    });
  },

  // 跳转创建
  goToCreate() {
    wx.navigateTo({
      url: '/pages/create/index?type=anniversary'
    });
  },

  onShareAppMessage() {
    return {
      title: '聚了吗 - 灵动纪念日',
      path: '/pages/anniversary/index'
    };
  }
});